#!/usr/bin/env python3
# -*- coding:utf-8 -*-

from flask import Flask
#初始化
app = Flask(__name__)

@app.route('/')
def index():
	return '<h1>Hello World!</h1>'

@app.route('/user/<name>')
def user(name):
	return '<h1>Hello,%s!</h1>'%name

#启动服务器
if __name__=='__main__':
	app.run(debug=True,port=8000)
